### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
It looks like that the [project homepage](http://users.telenet.be/on4qz/qsstv/) started returning 404 for some reason.

**Comment by xylo04** [comment]
The source download site is having issues: http://users.telenet.be/on4qz/home.html

**Comment by travier** [comment]
Note that we're still testing the 5.15-22.08 Runtime and we haven't announced it yet.

**Comment by AsciiWolf** [comment]
Thanks for the info, Timothée. I did not realize this. I have already switched some of my Flatpaks to 5.15-22.08 and everything seems to work fine (except one issue that is not related to the 5.15-22.08 runtime).

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
Tested and seems to work fine.

**Pull request merged**
